### ISSUE TITLE
podview window opens too wide on dual monitors

### ISSUE THREAD

**Issue by devel-chm** [dk/Prima#40] opened 2016-03-09 19:08 UTC
I have a dual monitor setup and the initial window size selected running "podview Prima" or whatever always spans 1 1/2 monitors in width.  This blocks my other windows and is wasteful since about 1/2 the width of either monitor by itself is more than sufficient to display the POD documentation.

Is there a way to control the window size (I didn't find one searching the manual)?  Is there a reason that the default cannot be "smarter" by setting an upper bound on the width of the text displayed?

**Comment by dk** [comment] 2016-03-09 19:21
There's a way to query the monitor setup with $::application->get_monitor_rects and adjusting the window to one's needs. However this is not the defaults, and works only if you have compiled Prima with xrandr extension. As for why this is not the default, simply because it was overlooked. I'll take a look at it when I'll have a dual monitor setup for testing.

**Comment by devel-chm** [comment] 2016-03-10 22:42
It might be simpler to just cap the size of the window based on the number
of characters text across and down.  That wouldn't need fancy xrandr
support and would get effectively the same result---too wide windows are
not created.  Thanks for taking a look.

--Chris

**Comment by dk** [comment] 2016-03-11 06:46
Yes, that would work for podview. I was looking at a more generic change in behavior, to not create too wide windows as a common default. The commit I've applied should (theoretically) do that, but I didn't test it on dual setup yet. If you could find time to try it as see if it works as intended, please do.

**Comment by dk** [comment] 2016-03-11 17:20
Tested on the dual setup, looks okay. I'm closing the ticket.

**Comment by devel-chm** [comment] 2016-10-26 15:24
I still have this problem with Prima 1.49 on a dual monitor setup with cygwin64/win7 with XWin running in -multiwindow mode.  This is the mode where the root X window is hidden and each of the client windows appear in their own win7 window.  If there were an option to set the desired size or an environment variable that would work.

**Comment by devel-chm** [comment] 2016-10-26 15:29
For example, with 2 1920 wide monitors, the xwininfo for the podview window is:

`xwininfo: Window id: 0x1e0000d "POD viewer - Moo"

  Absolute upper-left X:  8
  Absolute upper-left Y:  172
  Relative upper-left X:  8
  Relative upper-left Y:  172
  Width: 2880
  Height: 923
  Depth: 24
  Visual: 0x21
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x20 (installed)
  Bit Gravity State: ForgetGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +8+172  -952+172  -952-105  +8-105
  -geometry 2880x923+8+172
`

**Comment by dk** [comment] 2016-10-26 17:23
Hi, so, if I add support for parsing geometry, Xt-style ( WxH+X+Y ), would that work for you?

**Comment by dk** [comment] 2016-11-03 17:18
Please take a look at it if it works for you.

/dk

**Comment by devel-chm** [comment] 2016-11-05 13:35
It works.  Would it be possible to not require the position options and let the system put the window where the window manager wants to?  The docs for the option should specify that the units are pixels.

Thanks for the fix!

**Closed** 2016-11-05 13:42 UTC

**Comment by devel-chm** [comment] 2016-11-05 13:50
Perfect and wonderful!  Thanks, Dmitry!

**Comment by dk** [comment] 2016-11-05 14:07
You're welcome :)

**Comment by devel-chm** [comment] 2016-11-05 14:10
I don't know if this is related but podview with Prima 1.49 now segfaults on exit.  When I run from the build directory I get this

>  perl -Mblib utils/podview -geometry=1000x800 Moo
> X Error: BadWindow (invalid Window parameter), request: 4(X_DestroyWindow), between unix/apc_widget.c:564 and unix/apc_widget.c:571

This may be more a 1.45 vs 1.49 issue since I just upgraded to try out the app-shadertoy work by Max.

**Comment by dk** [comment] 2016-11-05 16:33
Whoops, that was a bug :) Thank you for reporting!

/dk
